# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodspark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='password',
            field=models.CharField(default='password', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='res_type',
            field=models.CharField(choices=[('B', 'Bar'), ('R', 'Restaurant'), ('C', 'Cafe')], max_length=1),
        ),
    ]
