# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodspark', '0002_auto_20170227_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(default='here'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='kgp', max_length=100),
            preserve_default=False,
        ),
    ]
