# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 17:02
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('foodspark', '0006_restaurant_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodlist', models.CharField(max_length=500, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('amount', models.IntegerField(default=0)),
                ('ordertime', models.TimeField(default=datetime.datetime(2017, 2, 27, 22, 32, 50, 745594))),
                ('deliverystatus', models.CharField(choices=[('p', 'Pending'), ('d', 'Delivered')], default='p', max_length=1)),
                ('paymentstatus', models.CharField(choices=[('P', 'Paid'), ('N', 'Not Paid')], default='N', max_length=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodspark.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='res_type',
            field=models.CharField(choices=[('B', 'Bar'), ('R', 'Restaurant'), ('C', 'Cafe')], default='R', max_length=1),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodspark.Restaurant'),
        ),
    ]
