# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 18:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodspark', '0008_auto_20170228_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='image',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='/home/projjal/Projects/Foodspark/foodspark/static/img', upload_to=b''),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordertime',
            field=models.TimeField(default=datetime.datetime(2017, 2, 28, 23, 53, 30, 642259)),
        ),
    ]
