# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 04:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodspark', '0009_auto_20170228_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='image',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='imgurl',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordertime',
            field=models.TimeField(default=datetime.datetime(2017, 3, 1, 10, 28, 27, 360250)),
        ),
    ]
