# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodspark', '0011_auto_20170301_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paymentstatus',
        ),
        migrations.AlterField(
            model_name='order',
            name='ordertime',
            field=models.TimeField(),
        ),
    ]
