# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodspark', '0012_auto_20170301_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='ordercount',
            field=models.IntegerField(default=0),
        ),
    ]
