# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodspark', '0013_fooditem_ordercount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderdate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
